# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weblink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('baskets', models.ManyToManyField(blank=True, related_name='weblinks', to='hit.Basket')),
            ],
        ),
    ]
