# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otcore.relation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='hit.Basket')),
            ],
            options={
                'ordering': ('relationtype', 'source', 'destination'),
            },
        ),
        migrations.CreateModel(
            name='RelatedHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_hit', to='hit.Hit')),
            ],
            options={
                'ordering': ('relationtype', 'source', 'destination'),
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.CharField(default='Generic', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('role_from', models.CharField(default='Generic', max_length=100)),
                ('role_to', models.CharField(default='Generic', max_length=100)),
                ('symmetrical', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('rtype',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='relationtype',
            unique_together=set([('rtype', 'role_from', 'role_to')]),
        ),
        migrations.AddField(
            model_name='relatedhit',
            name='relationtype',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='relation.RelationType'),
        ),
        migrations.AddField(
            model_name='relatedhit',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_hit', to='hit.Hit'),
        ),
        migrations.AddField(
            model_name='relatedbasket',
            name='relationtype',
            field=models.ForeignKey(default=otcore.relation.models.get_default_type, on_delete=django.db.models.deletion.SET_DEFAULT, to='relation.RelationType'),
        ),
        migrations.AddField(
            model_name='relatedbasket',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='hit.Basket'),
        ),
        migrations.AlterUniqueTogether(
            name='relatedhit',
            unique_together=set([('relationtype', 'source', 'destination')]),
        ),
        migrations.AlterUniqueTogether(
            name='relatedbasket',
            unique_together=set([('relationtype', 'source', 'destination')]),
        ),
    ]
