# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedbasket',
            name='display',
        ),
        migrations.AddField(
            model_name='relatedbasket',
            name='forbidden',
            field=models.BooleanField(default=False),
        ),
    ]
