# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otcore.relation.models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0003_auto_20160519_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedbasket',
            name='relationtype',
            field=models.ForeignKey(default=otcore.relation.models.get_default_type, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='related_baskets', to='relation.RelationType'),
        ),
    ]
