# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otcore.relation.models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0004_auto_20160831_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedhit',
            name='relationtype',
            field=models.ForeignKey(blank=True, default=otcore.relation.models.get_default_type, on_delete=django.db.models.deletion.SET_DEFAULT, to='relation.RelationType'),
        ),
    ]
