# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 04:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occurrence', '0012_auto_20160812_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_location', models.CharField(max_length=128)),
                ('epub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inedexes', to='occurrence.Document')),
            ],
        ),
        migrations.CreateModel(
            name='IndexPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('pagenumber_pre_strings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('xpath_entry', models.CharField(blank=True, max_length=255)),
                ('xpath_entry_element', models.CharField(max_length=80)),
                ('xpath_term', models.CharField(blank=True, max_length=255)),
                ('xpath_occurrence_link_element', models.CharField(default='a[@href]', max_length=50)),
                ('xpath_occurrence_link_attribute', models.CharField(default='@href', max_length=50)),
                ('xpath_subentry', models.CharField(blank=True, max_length=255)),
                ('xpath_see', models.CharField(blank=True, max_length=50)),
                ('xpath_seealso', models.CharField(blank=True, max_length=50)),
                ('separator_between_entry_and_occurrences', models.CharField(blank=True, max_length=50)),
                ('separator_between_occurrences', models.CharField(blank=True, max_length=50)),
                ('separator_before_first_subentry', models.CharField(blank=True, max_length=50)),
                ('separator_between_subentries', models.CharField(blank=True, max_length=50)),
                ('separator_between_sees', models.CharField(blank=True, max_length=50)),
                ('separator_between_seealsos', models.CharField(blank=True, max_length=50)),
                ('indicator_of_occurrence_range', models.CharField(default='&#8212;', max_length=50)),
                ('indicator_of_see', models.CharField(blank=True, max_length=50)),
                ('indicator_of_seealso', models.CharField(blank=True, max_length=50)),
                ('is_subentry_a_separate_element', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
