# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0002_auto_20161109_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpattern',
            name='xpath_entry_element',
        ),
        migrations.RemoveField(
            model_name='indexpattern',
            name='xpath_term',
        ),
    ]
