# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_auto_20161109_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpattern',
            name='occurrence_link_class',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
