# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0004_indexpattern_occurrence_link_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpattern',
            name='separator_see_subentry',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
