# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0005_indexpattern_separator_see_subentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexpattern',
            old_name='xpath_subentry',
            new_name='subentry_class',
        ),
    ]
