# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 19:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0006_auto_20161109_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpattern',
            name='see_also_split_string',
        ),
        migrations.AddField(
            model_name='indexpattern',
            name='see_also_split_strings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[], size=None),
            preserve_default=False,
        ),
    ]
