# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 03:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0007_auto_20161111_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpattern',
            name='indicator_of_occurrence_range',
        ),
        migrations.RemoveField(
            model_name='indexpattern',
            name='separator_between_occurrences',
        ),
        migrations.AddField(
            model_name='indexpattern',
            name='indicators_of_occurrence_range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='-', max_length=50), default=[], size=None),
            preserve_default=False,
        ),
    ]
