# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0008_auto_20161111_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexpattern',
            old_name='occurrence_link_class',
            new_name='xpath_occurrence_link',
        ),
    ]
