# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0009_auto_20161111_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpattern',
            name='is_subentry_a_separate_element',
            field=models.BooleanField(),
        ),
    ]
