# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0010_auto_20161116_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpattern',
            name='xpath_occurrence_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
