# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0013_auto_20161129_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpattern',
            name='inline_see_also_end',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='indexpattern',
            name='inline_see_also_start',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='indexpattern',
            name='inline_see_end',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='indexpattern',
            name='inline_see_start',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
