# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 20:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0014_auto_20161201_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpattern',
            name='subentry_class',
        ),
        migrations.AddField(
            model_name='indexpattern',
            name='subentry_classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[], size=None),
            preserve_default=False,
        ),
    ]
