# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0015_auto_20161202_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='indexpattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='manuscripts.IndexPattern'),
        ),
    ]
