# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0016_index_indexpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpattern',
            name='pagenumber_css_selector_pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='indexpattern',
            name='pagenumber_tag_pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='indexpattern',
            name='pagenumber_xpath_pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
