# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_unique_indicator', models.CharField(max_length=25, unique=True)),
                ('content_descriptor', models.CharField(max_length=25)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('doctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.DocType')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(blank=True, null=True)),
                ('filepath', models.TextField(max_length=255)),
                ('localid', models.CharField(blank=True, max_length=255, null=True)),
                ('context', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='at_location', to='occurrence.Content')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='occurrence.Document')),
            ],
            options={
                'ordering': ('sequence_number',),
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_in_content', models.CharField(blank=True, default='Not Found', max_length=25, null=True)),
                ('basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurs', to='hit.Basket')),
                ('input_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputs', to='occurrence.Location')),
                ('output_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='occurrence.Location')),
                ('processing_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processings', to='occurrence.Location')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Mention', max_length=30, unique=True)),
                ('main', models.BooleanField(default=False)),
                ('occs', models.ManyToManyField(blank=True, related_name='role', to='occurrence.Occurrence')),
            ],
        ),
    ]
