# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrencerole',
            name='occs',
        ),
        migrations.DeleteModel(
            name='OccurrenceRole',
        ),
    ]
