# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0002_auto_20160415_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurs', to='hit.Basket'),
        ),
    ]
