# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0006_auto_20160614_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='output_location',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='processing_location',
        ),
    ]
