# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0008_auto_20160615_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('localid', 'filepath')]),
        ),
    ]
