# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0009_auto_20160617_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['filepath', 'localid']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='occurrence',
            order_with_respect_to='location',
        ),
    ]
