# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0011_auto_20160812_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_unique_indicator',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True),
        ),
    ]
