# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0013_auto_20161206_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['sequence_number']},
        ),
    ]
