# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otx_xml', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmlpattern',
            old_name='xpath_location',
            new_name='xpath_locations',
        ),
        migrations.AddField(
            model_name='xmlpattern',
            name='xpath_content_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xmlpattern',
            name='xpath_location_localid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
