# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otx_xml', '0002_auto_20161027_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlpattern',
            name='name',
            field=models.CharField(blank=True, default='default', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='xmlpattern',
            name='xpath_author',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xmlpattern',
            name='xpath_content',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xmlpattern',
            name='xpath_content_header',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xmlpattern',
            name='xpath_location_localid',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xmlpattern',
            name='xpath_locations',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xmlpattern',
            name='xpath_occurrence',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xmlpattern',
            name='xpath_title',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xmlpattern',
            name='xpath_topic',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
