# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttype',
            name='ttype',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
