# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 12:42
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import otcore.hit.models
import otcore.lex.lex_utils


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=512, populate_from=otcore.hit.models.pop_from, slugify=otcore.lex.lex_utils.lex_slugify, unique=True),
        ),
    ]
