# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0003_auto_20160429_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.CharField(default='Generic', max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hit',
            name='angle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hit.Angle'),
        ),
    ]
