# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0006_auto_20160520_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['topic_hits__name']},
        ),
        migrations.AlterField(
            model_name='hit',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_hits', to='hit.Basket'),
        ),
    ]
