# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0007_auto_20160606_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
