# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0008_basket_preferred_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
    ]
