# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0009_auto_20160609_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='scope',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hit.Scope'),
        ),
    ]
