# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0011_auto_20160623_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='kind',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
