# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0012_auto_20160624_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['display_name']},
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='preferred_name',
            new_name='display_name',
        ),
    ]
