# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otcore.hit.models


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0013_auto_20160628_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='scope',
            field=models.ForeignKey(default=otcore.hit.models.get_default_scope, on_delete=django.db.models.deletion.CASCADE, to='hit.Scope'),
        ),
    ]
