# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0014_auto_20160729_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='label',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
