# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otcore.hit.models


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0015_auto_20161021_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='scope',
            field=models.ForeignKey(default=otcore.hit.models.get_default_scope, on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='hit.Scope'),
        ),
    ]
