# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 18:15
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import otcore.lex.lex_utils


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0016_auto_20170119_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=512, populate_from='name', slugify=otcore.lex.lex_utils.lex_slugify),
        ),
    ]
