# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-26 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0017_auto_20170131_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
