# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acronym',
        ),
        migrations.DeleteModel(
            name='Expression',
        ),
        migrations.DeleteModel(
            name='Irregular',
        ),
    ]
