# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0002_auto_20160418_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acronym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=20, unique=True)),
                ('developed', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('rationale', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('acronym',),
            },
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(db_index=True, max_length=500, unique=True)),
            ],
            options={
                'ordering': ('expression',),
            },
        ),
        migrations.CreateModel(
            name='Irregular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=255, unique=True)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('word',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='irregular',
            unique_together=set([('word', 'token')]),
        ),
    ]
