# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0003_auto_20160429_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=256)),
                ('recognizer', models.CharField(max_length=100)),
                ('replacer', models.SlugField(allow_unicode=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Acronym',
        ),
        migrations.DeleteModel(
            name='Expression',
        ),
        migrations.DeleteModel(
            name='Irregular',
        ),
        migrations.AlterField(
            model_name='stopword',
            name='word',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
