# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lex', '0004_auto_20170427_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizer',
            name='passthrough',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recognizer',
            name='priority',
            field=models.FloatField(default=1.0),
        ),
    ]
