# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otx_review', '0003_auto_20161215_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('topic_set', models.CharField(choices=[('A', 'All Topics'), ('R', 'All Reviewed Topics'), ('U', 'Revied But Unchanged Topics Only'), ('C', 'Reviewed and Changed Topics Only')], max_length=1)),
                ('location', models.FileField(upload_to='reports')),
            ],
        ),
    ]
