# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otx_review', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='topic_set',
            field=models.CharField(choices=[('A', 'All Topics'), ('R', 'All Reviewed Topics'), ('U', 'Reviewed But Unchanged Topics Only'), ('C', 'Reviewed and Changed Topics Only')], max_length=1),
        ),
    ]
