# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otx_epub.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occurrence', '0012_auto_20160812_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPub',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='occurrence.Document')),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('source', models.FileField(storage=otx_epub.storage.OverwriteStorage(), upload_to='/tmp/epubs')),
                ('oebps_folder', models.CharField(blank=True, max_length=50)),
                ('manifest', models.CharField(blank=True, max_length=50)),
            ],
            bases=('occurrence.document',),
        ),
    ]
