# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otx_epub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epub',
            name='contents',
            field=models.FilePathField(allow_files=False, allow_folders=True, default='', path='/tmp/epubs', recursive=True),
            preserve_default=False,
        ),
    ]
