# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import otx_epub.storage


class Migration(migrations.Migration):

    dependencies = [
        ('otx_epub', '0002_epub_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epub',
            name='contents',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/vagrant/nyu/media/epub_decompressed', recursive=True),
        ),
        migrations.AlterField(
            model_name='epub',
            name='manifest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='epub',
            name='oebps_folder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='epub',
            name='source',
            field=models.FileField(storage=otx_epub.storage.OverwriteStorage(), upload_to='epubs'),
        ),
    ]
