# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import otx_epub.storage


class Migration(migrations.Migration):

    dependencies = [
        ('otx_epub', '0003_auto_20161027_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epub',
            name='source',
            field=models.FileField(storage=otx_epub.storage.OverwriteStorage(), upload_to='/vagrant/nyu/media/epubs'),
        ),
    ]
