# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otx_epub', '0004_auto_20161102_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epub',
            name='contents',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
