# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import otx_epub.storage


class Migration(migrations.Migration):

    dependencies = [
        ('otx_epub', '0005_auto_20161103_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epub',
            name='source',
            field=models.FileField(storage=otx_epub.storage.OverwriteStorage(), upload_to='/vagrant/media/epubs'),
        ),
    ]
